server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers,env,beans
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: autochannel

sftp:
  host: localhost
  port: 2222
  username: autochannel
  password: password
  remote-dir: upload

spring:
  profiles:
    active: mock
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:mariadb://localhost:3306/autochannel?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: autochannel
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
